/**
 * KALLAX Dead-Code Runtime Sentinel (EPIC-131-B)
 *
 * 思路 (主公 2026-07-20 抓的):
 *   "死代码、类型错误等等不被调用到的时候不会暴露"
 *
 * 治根: 每个被 `export` 的 module symbol 必须被一个 `it()` sentinel test 至少 import 一次。
 *
 * 跟 docs/reference/epic-131-sentinel-coverage.json (auto-generated by scripts/scan-dead-code.sh)
 * 一起读 — 提供精确 list。
 *
 * 测试规则:
 *   - import 每个 module (trigger static load)
 *   - assert typeof === 'function' 或 'object' 等, 强制 module 真存在
 *   - fail 立即, 不让 sentinel module 静默地不被加载
 */
import * as dimensions from '../src/core/master-verify/dimensions.js';

describe('Dead-Code Sentinel — master-verify/dimensions', () => {
  it('every exported symbol is loadable', () => {
    // 静态 sentinel: 模块能被加载, 所有 export 都存在
    expect(typeof dimensions.parseArgs).toBe('function');
    expect(typeof dimensions.checkL1).toBe('function');
    expect(typeof dimensions.checkL2).toBe('function');
    expect(typeof dimensions.checkL3).toBe('function');
    expect(typeof dimensions.checkL4).toBe('function');
    expect(typeof dimensions.checkL5).toBe('function');
    expect(typeof dimensions.checkL6).toBe('function');
    expect(typeof dimensions.calculateNetValue).toBe('function');
  });

  it('parseArgs --flag=value pairs (pure function, no IO)', () => {
    // sentinel-level guard: 静态 sentinel 检测 dead code, parseArgs 是纯函数必过
    const r = dimensions.parseArgs(['--foo=bar', '--baz', 'qux']);
    expect(r.get('foo')).toBe('bar');
    expect(r.get('baz')).toBe('qux');
  });

  it('parseArgs ignores non-flag args', () => {
    const r = dimensions.parseArgs(['positional', '--x', '1', '--y']);
    expect(r.has('x')).toBe(true);
    expect(r.get('x')).toBe('1');
    expect(r.get('y')).toBe('true');
  });

  it('calculateNetValue returns {value, improvement}', () => {
    // 纯计算, 不依赖外部命令 — must-pass sentinel
    const r = dimensions.calculateNetValue();
    expect(typeof r.value).toBe('number');
    expect(typeof r.improvement).toBe('number');
  });
});
