#!/bin/bash
# team-standup-2026-06-12.sh — Master 召唤团队 + 任务分配看板
# 主公 2026-06-12 拍"你来召唤团队拆卡领任务开工"
# Master session 内写团队看板, Conductor 容器起来后自动跑
set -euo pipefail

KALLAX_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$KALLAX_ROOT"

echo "=========================================="
echo " KALLAX Master 召唤团队 — 2026-06-12"
echo "=========================================="
echo ""
echo "主公拍: 你来召唤团队拆卡领任务开工"
echo "Master 决策: 启 9 dispatch (6 原有 + 3 EPIC-038), 1 conductor + 4 Performer 团队"
echo ""

# 1. 团队清单
echo "=========================================="
echo " 团队 (1 conductor + 4 Performer types, 1+4 容量):"
echo "=========================================="
echo ""
echo "  🎯 Master_main (master)"
echo "     职责: 协调 + 拍战略 + 强验证 6 维度"
echo "     session: master_77704 (主公)"
echo "     实例: .kallax/instances/master_main/"
echo ""
echo "  🎼 Conductor_main (conductor)"
echo "     职责: 派单 + 监控 + 拍板 (80% AI delegation)"
echo "     session: conductor_77704 (持续 in_progress)"
echo "     实例: .kallax/instances/conductor_main/"
echo "     inbox: .kallax/queue/inbox/conductor_main/ (9 票)"
echo ""
echo "  🔧 Performer-EPIC-034 (backend, EPIC-034-C/D/B)"
echo "     职责: Gap 9 接受+完善+思考 联合载体"
echo "     worktree: .kallax/worktrees/performer-EPIC-034"
echo "     ticket: EPIC-034-C (P0, 6h) → EPIC-034-D (P0, 6h) → EPIC-034-B (P1, 4h)"
echo ""
echo "  🔧 Performer-EPIC-035 (backend, EPIC-035-A merged with Rule 14)"
echo "     职责: Gap 9 接受 + Hang 防御 L1+L2 联合载体"
echo "     worktree: .kallax/worktrees/performer-PHASE-006 (新)"
echo "     ticket: EPIC-035-A (P1, 8h merged: worktree_role 4h + Rule 14 4h)"
echo ""
echo "  🔧 Performer-EPIC-036 (backend, EPIC-036-A + 038-B 合并)"
echo "     职责: Gap 9 判断 + Performer sub-role 联合载体"
echo "     worktree: .kallax/worktrees/performer-PHASE-006 (新)"
echo "     ticket: EPIC-036-A (P1, 6h) + EPIC-038-B (P1, 8h) = 14h"
echo ""
echo "  🔧 Performer-EPIC-037 (security, EPIC-037-A + 038-C 合并)"
echo "     职责: Gap 9 增加/完善 + Auditor 角色 + 跨项目 联合载体"
echo "     worktree: .kallax/worktrees/performer-PHASE-006 (新)"
echo "     ticket: EPIC-037-A (P1, 6h) + EPIC-038-C (P1, 8h) = 14h"

# 2. 任务分配 (总 9 dispatch / 6 票 ticket 实际)
echo ""
echo "=========================================="
echo " 任务分配 (9 dispatch / 6 ticket):"
echo "=========================================="
echo ""
echo "EPIC-034 链 (Gap 9 接受+完善+思考, Performer-EPIC-034):"
echo "  📋 EPIC-034-C  P0  6h  blocked:none       ← 真创建 6 generated + 修 audit stale"
echo "  📋 EPIC-034-D  P0  6h  blocked:034-C       ← binary 同步 (Master 预拆)"
echo "  📋 EPIC-034-B  P1  4h  blocked:035-A       ← M1 Recall 61%→80%+, 跟 034-D 协同"
echo ""
echo "EPIC-035 链 (Gap 9 接受 + Hang 防御 L1+L2, Performer-EPIC-035):"
echo "  📋 EPIC-035-A  P1  8h  blocked:034-B       ← worktree_role 4h + Rule 14 4h (merged)"
echo ""
echo "EPIC-036 链 (Gap 9 判断 + Performer sub-role, Performer-EPIC-036):"
echo "  📋 EPIC-036-A  P1  6h  blocked:035-A       ← 跨 worktree 派单"
echo "  📋 EPIC-038-B  P1  8h  blocked:038-A       ← 4 类 Performer + 1+4 容量 (跟 036-A 一起做)"
echo ""
echo "EPIC-037 链 (Gap 9 增加/完善 + Auditor, Performer-EPIC-037):"
echo "  📋 EPIC-037-A  P1  6h  blocked:036-A       ← 持续 audit (redaction + KPI)"
echo "  📋 EPIC-038-C  P1  8h  blocked:038-B       ← Auditor 角色 + 跨项目 import (跟 037-A 一起做)"
echo ""
echo "总 wall time: ~32h (4 Performer 并行 + L1 战术拆 commit)"
echo "总 work hours: ~62h (3+14+14+14 h)"

# 3. 关键交接
echo ""
echo "=========================================="
echo " 关键交接 (Conductor 起来后):"
echo "=========================================="
echo ""
echo "  1. Conductor 拉 9 dispatch (跟 algorithms 80% AI delegation)"
echo "  2. 按 blocked_by 链串行派单:"
echo "     Wave 1: EPIC-034-C → EPIC-035-A"
echo "     Wave 2: EPIC-034-D (P0 接力)"
echo "     Wave 3: EPIC-034-B (跟 034-D 协同)"
echo "     Wave 4: EPIC-036-A → EPIC-038-B (跟 035-A 一起)"
echo "     Wave 5: EPIC-037-A → EPIC-038-C (跟 036-A 一起)"
echo "  3. 2 Performer 容器 (1+2 容量) 拉各自 inbox 跑 worktree"
echo "  4. EPIC-035/036/037 跟 EPIC-038 合并 ticket 减少独立跑次数"
echo "  5. L1 战术 (拆 commit) 跑前必过 decide-on-spawn.sh (Wave 1 EPIC-035-A 完工后)"

# 4. Master 强验证 6 维度
echo ""
echo "=========================================="
echo " Master 强验证 6 维度 (Rule 11 v2.1):"
echo "=========================================="
echo ""
echo "  L1 git log --oneline -1 看 SHA 真变"
echo "  L2 git show HEAD:file | grep 看内容真改"
echo "  L3 跑全量 E2E (跟 ticket AC 逐条)"
echo "  L4 check-fact-forcing-preflight.sh + 4 anti-fab + Rule 14/15"
echo "  L5 任何 Rule 1/11 边界事件标 + 留 LESSONS-LEARNED 草稿"
echo "  L6 报假 PASS = FAIL, 跟 Rule 9e 自验证联动"

# 5. miao HEAD
MIAO_HEAD=$(git rev-parse --short HEAD)
echo ""
echo "=========================================="
echo " miao HEAD: $MIAO_HEAD"
echo "=========================================="
echo ""
echo "  5a1103a (4 层接手 Rule 15 + Performer sub-role + Auditor 角色, 主公拍 A 立即派)"
echo "  6f5b99f (5 能力研究 + Rule 15 草案, 497 行)"
echo "  79c2ce9 (Performer hang 根因 + 4 防御 + Rule 14 草案, 307 行)"
echo "  37f0228 (Top 4 EPIC + team-kickoff v1)"
echo "  35afb6f (主公 流程逻辑 战略转向, Gap 8 暂缓 + Gap 9 元能力)"
echo "  3c61cca (PHASE-006-ROADMAP 5 视角 + Master 仲裁)"
echo "  3f35d6a (KALLAX-VS-INDUSTRY 5 痛点 × 业内 4 框架)"

# 6. 触发 Conductor 容器
echo ""
echo "=========================================="
echo " 触发 Conductor 容器 (一键):"
echo "=========================================="
echo ""
echo "  ! bash .kallax/hooks/session_start.sh --role conductor"
echo ""
echo "  Conductor 起来后:"
echo "    1. 拉 9 dispatch (从 conductor_main inbox)"
echo "    2. 算法派单 (3-layer matching, TrustScore highest)"
echo "    3. 派给 Performer-EPIC-034/035/036/037 4 类 (Rule 15 落地后)"
echo "    4. 2 Performer 容器 (1+2 容量) 跑 worktree"
echo "    5. Conductor merge feature → testing"
echo "    6. Master 强验证 6 维度 (本 session 持续)"

# 7. 任务清单 (主公可视化)
echo ""
echo "=========================================="
echo " 任务清单 (主公拍板后 Master 等):"
echo "=========================================="
echo ""
echo "  ✅ 1. 拆卡 (3 EPIC-038 + 3 EPIC 原有 = 6 ticket)"
echo "  ✅ 2. 派单 (9 dispatch 写 conductor_main inbox)"
echo "  ✅ 3. 团队清单 (1 master + 1 conductor + 4 Performer types)"
echo "  ⏳ 4. Conductor 容器触发 (主公开新 session)"
echo "  ⏳ 5. Performer 跑 worktree (4 类 × 1 容器)"
echo "  ⏳ 6. Conductor merge → testing"
echo "  ⏳ 7. Master 强验证 6 维度 (每 Wave 报 PASS 后)"
echo "  ⏳ 8. PHASE-007 review 触发 (6+ ticket 累计)"
