#!/usr/bin/env bash
# KALLAX Install — 框架部署脚本 (EPIC-126-D)
# 自动部署: expert-resolver + skill symlink + Node CLI link
# 用法: bash scripts/kallax-install.sh [--force]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INSTALL_MODE="${1:-user}"  # user | global

usage() {
  cat <<EOF
Usage: kallax-install.sh [--force]

Options:
  --force    强制覆盖已存在的 symlink
  --help     显示帮助

部署内容:
  1. expert-resolver.sh → ~/.local/bin/ (CLI)
  2. skill symlink → ~/.claude/skills/kallax
  3. Node CLI link (需要 node/ 已 build)

示例:
  bash scripts/kallax-install.sh              # 用户级安装
  sudo bash scripts/kallax-install.sh         # 全局安装 (需要 sudo)
EOF
  exit 1
}

FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    -h|--help) usage ;;
    *) echo "ERROR: unknown arg: $1" >&2; usage ;;
  esac
done

echo "=== KALLAX Install ==="
echo "Repo root: ${REPO_ROOT}"
echo ""

# 1. Deploy expert-resolver.sh
EXPERT_RESOLVER_SRC="${REPO_ROOT}/tools/expert-resolver.sh"
EXPERT_RESOLVER_DST="${HOME}/.local/bin/expert-resolver"

if [[ ! -f "${EXPERT_RESOLVER_SRC}" ]]; then
  echo "[FAIL] expert-resolver.sh not found: ${EXPERT_RESOLVER_SRC}" >&2
  exit 1
fi

  EXPERT_RESOLVER_DATA_JSON="${REPO_ROOT}/../kallax-experts/docs/experts/data.json"
  _do_install_resolver() {
    mkdir -p "$(dirname "${EXPERT_RESOLVER_DST}")"
    if [[ -f "${EXPERT_RESOLVER_DATA_JSON}" ]]; then
      sed "s|DATA_JSON = Path.*|DATA_JSON = Path(\"${EXPERT_RESOLVER_DATA_JSON}\")|" \
        "${EXPERT_RESOLVER_SRC}" > "${EXPERT_RESOLVER_DST}"
    else
      cp "${EXPERT_RESOLVER_SRC}" "${EXPERT_RESOLVER_DST}"
    fi
    chmod +x "${EXPERT_RESOLVER_DST}"
  }

  if [[ -L "${EXPERT_RESOLVER_DST}" ]] && [[ "${FORCE}" -eq 0 ]]; then
    echo "[SKIP] expert-resolver already installed: ${EXPERT_RESOLVER_DST}"
  elif [[ -L "${EXPERT_RESOLVER_DST}" ]] && [[ "${FORCE}" -eq 1 ]]; then
    rm "${EXPERT_RESOLVER_DST}"; _do_install_resolver
    echo "[OK] expert-resolver updated: ${EXPERT_RESOLVER_DST}"
  else
    _do_install_resolver
    echo "[OK] expert-resolver installed: ${EXPERT_RESOLVER_DST}"
  fi

  # 1b. Deploy build-experts.py (from sibling kallax-experts repo)
  BUILD_EXPERTS_SRC="${REPO_ROOT}/../kallax-experts/tools/build-experts.py"
  BUILD_EXPERTS_DST="${HOME}/.local/bin/build-experts"
  if [[ -f "${BUILD_EXPERTS_SRC}" ]]; then
    if [[ -L "${BUILD_EXPERTS_DST}" ]] && [[ "${FORCE}" -eq 0 ]]; then
      echo "[SKIP] build-experts already installed: ${BUILD_EXPERTS_DST}"
    else
      mkdir -p "$(dirname "${BUILD_EXPERTS_DST}")"
      cp "${BUILD_EXPERTS_SRC}" "${BUILD_EXPERTS_DST}"
      chmod +x "${BUILD_EXPERTS_DST}"
      echo "[OK] build-experts installed: ${BUILD_EXPERTS_DST}"
    fi
  fi

# 2. Skill symlink
SKILL_SRC="${REPO_ROOT}"
SKILL_DST="${HOME}/.claude/skills/kallax"

if [[ -L "${SKILL_DST}" ]]; then
  CURRENT_TARGET=$(readlink "${SKILL_DST}")
  if [[ "${CURRENT_TARGET}" == "${SKILL_SRC}" ]]; then
    echo "[SKIP] skill already symlinked: ${SKILL_DST} → ${SKILL_SRC}"
  else
    if [[ "${FORCE}" -eq 1 ]]; then
      rm "${SKILL_DST}"
      ln -s "${SKILL_SRC}" "${SKILL_DST}"
      echo "[OK] skill symlink updated: ${SKILL_DST} → ${SKILL_SRC}"
    else
      echo "[WARN] skill symlink exists but points elsewhere: ${SKILL_DST} → ${CURRENT_TARGET}"
      echo "       Use --force to overwrite"
    fi
  fi
elif [[ -d "${SKILL_DST}" ]]; then
  echo "[WARN] skill dir exists (not a symlink): ${SKILL_DST}"
  echo "       Cannot install. Remove it first or use --force"
  if [[ "${FORCE}" -eq 1 ]]; then
    rm -rf "${SKILL_DST}"
    ln -s "${SKILL_SRC}" "${SKILL_DST}"
    echo "[OK] skill symlink created: ${SKILL_DST} → ${SKILL_SRC}"
  fi
else
  mkdir -p "$(dirname "${SKILL_DST}")"
  ln -s "${SKILL_SRC}" "${SKILL_DST}"
  echo "[OK] skill symlinked: ${SKILL_DST} → ${SKILL_SRC}"
fi

# 3. Node CLI (如果已 build)
NODE_CLI_SRC="${REPO_ROOT}/node/dist/index.js"
NODE_CLI_DST="${HOME}/.local/bin/kallax"

if [[ -f "${NODE_CLI_SRC}" ]]; then
  if [[ -L "${NODE_CLI_DST}" ]] && [[ "${FORCE}" -eq 0 ]]; then
    echo "[SKIP] kallax CLI already linked: ${NODE_CLI_DST}"
  else
    mkdir -p "$(dirname "${NODE_CLI_DST}")"
    # 用 node 运行: 创建 wrapper script
    cat > "${NODE_CLI_DST}" <<WRAPPER
#!/usr/bin/env bash
# KALLAX CLI wrapper — generated by kallax-install.sh
exec node "${NODE_CLI_SRC}" "\$@"
WRAPPER
    chmod +x "${NODE_CLI_DST}"
    echo "[OK] kallax CLI installed: ${NODE_CLI_DST}"
  fi
else
  echo "[WARN] Node CLI not built. Run: cd node && npm install && npm run build"
fi

echo ""
echo "=== Install Complete ==="
echo ""
echo "下一步:"
echo "  1. 确保 ~/.local/bin 在 PATH 中: echo \$PATH | tr ':' '\\n' | grep local"
echo "  2. 验证: expert-resolver \"SQL注入\" --json"
echo "  3. 验证: kallax --version"
